[package]
name = "commentstats"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"
resolver = "2"

[dependencies]
anyhow = "1.0.40"
chrono = { version = "0.4.19", features = ["serde"] }
git2 = { version = "0.13.17", default-features = false }
itertools = "0.10.0"
plotters = { version = "0.3.0", default-features = true }
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
structopt = "0.3.21"
tokei = "12.1.2"

[profile.release]
lto = true
