[package]
name = "commentstats"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"
resolver = "2"

[dependencies]
anyhow = "1.0.40"
chrono = { version = "0.4.19", default-features = false, features = ["clock", "serde", "std"] }
git2 = { version = "0.13.17", default-features = false }
itertools = "0.10.0"
num_cpus = "1.13.0"
once_cell = "1.7.2"
pbr = "1.0.4"
plotters = { version = "0.3.0", default-features = false, features = [
    "datetime",
    "line_series",
    "svg_backend",
] }
rayon = "1.5.0"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
structopt = "0.3.21"
tokei = "12.1.2"
zstd = { version = "0.6.1", default-features = false, features = ["zstdmt"] }

[profile.release]
lto = true
